### ISSUE TITLE
Phase - II (Roadmap: Mid August 2022)

### ISSUE THREAD

**Issue by Asok17** [addonify/addonify-wishlist#35]
- [ ] Add to wishlist button shortcode to add wishlist button anywhere
- ~~[ ] Share wishlist page across social sites such as facebook, twitter, pinterest, etc.~~
- ~~[ ] Select what to display in the wishlist page~~
- ~~[ ] Toast popup when added to wishlist~~

**Comment by Asok17** [comment]
- [x] 1. Undo remove from wishlist action. Add undo notice timeout time option, action text, and undo link label.
- [x] 2. Create wishlist table on plugin activation and plugin upgrade.
- [x] 3. Migrate logged in user’s data into wishlist table.
- ~~[ ] 4. For 0 value of the setting, **Save Wishlist Cookie for [x] days**, wishlist data remains forever.~~
- [x] 5. When Add to Wishlist button is clicked, before the product has been added into wishlist, display a loader.
- [x] 6. Add select option for icon position on Add to Wishlist button.
- [x] 7. Empty wishlist text in sidebar. Add text option in setting page.
- [x] 8. Empty wishlist text in wishlist page. Add text option in setting page.
- [x] 9. When wishlist is empty, display a link, so that user can navigate. Add button label and button link options in setting page.
- [x] 10. Add text option for label to button for clearing wishlist in wishlist page.
- ~~[ ] 11. Add toggle option for enabling wishlist notice in sidebar.~~
- [x] 12. Display product stock status below price in sidebar.
- [x] 13. Empty Wishlist button is being displayed when last element in the wishlist has been removed. It should not be displayed if the wishlist is empty.

**Comment by diwakar2000** [comment]
issue 12 fixed in commit #200

**Comment by Asok17** [comment]
**Some changes to made**:

- [x] 1. Remove the option, `Save Wishlist Cookie for [ x ] days`. Remove everything associated with this option.
- [x] 2. Change data migration notice to - `The new version of Addonify Wishlist requires database update.`. Below the text add button link, with label - `Update`.

@diwakar2000

**Comment by Asok17** [comment]
**Data migration issues**:

- [x] 1. When table is created, two wishlists are created for the current user. One has the name `default_wishlist`, and another with the name `Default Wishlist`. Only one wishlist should be created and all products from the meta should be moved into the wishlist.
- [x] 2. If a user logs in, only his wishlist is created, products didn't migrate.

@diwakar2000

**Comment by Asok17** [comment]
- [x] After update, but before the database table had been created. There is a database error as below:

```
WordPress database error Table 'local.wp_addonify_wishlist_table' doesn't exist for query SELECT * FROM
wp_addonify_wishlist_table WHERE  site_url = 'http://wptest.local'  AND  product_id = 24  AND  user_id = 1
 made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'),
include('/plugins/woocommerce/templates/archive-product.php'), wc_get_template_part, load_template,
require('/plugins/woocommerce/templates/content-product.php'), do_action('woocommerce_after_shop_loop_item'),
WP_Hook->do_action, WP_Hook->apply_filters, Addonify_Wishlist_Public_Deprecated->render_add_to_wishlist_button,
do_action('addonify_wishlist_render_wishlist_button'), WP_Hook->do_action, WP_Hook->apply_filters,
addonify_wishlist_render_add_to_wishlist_button, Addonify\Wishlist->get_wishlist_id_from_product_id,
Addonify\Wishlist::get_row
```
Need to fix it. @diwakar2000

**Comment by Asok17** [comment]
- [x] In multisite, for different sites, different tables with suffix, `addonify_wishlist_table`, are being created. If a user has wishlist data of different sites, each table have created wishlists for those sites too. This should not be the way. Either a table should have record of that site only. Or a single table should be created for all the sites and records should be kept for all those sites in that single table.

@diwakar2000 @Asok17

**Comment by Asok17** [comment]
- [x] Add a choice `none` in dropdown,` After Add to Wishlist Action`. If this choice is selected, do nothing once add to wishlist button is clicked.
- [x] Move options, `Show wishlist emptying button` and `Wishlist Emptied Text` before the option `Clear Wishlist Button Label`.

@Asok17 @diwakar2000

**Comment by Asok17** [comment]
Add new option for `Save for Later` button. The button will be displayed in the cart page.

Following are the options need to be added:

- [x] **1. Enable save for later button**
- [x] **2. Label for save for later button**
- [x] **3. Position of save for later button**

**Note:** Do not display the button if the product is already in the wishlist.

Create a new section called, **Save for Later**, in the **General Settings**. Then add above mentioned options inside the section.

**1. Enable save for later button**
Type - Toggle Switch
Default Value - False

**2. Label for save for later button**
Type - Text
Default Value - Save for Later
Placeholder - Save for Later

**3. Position of save for later button**
Type - Select
Default Value - after_product_name
Choices - `array( 'after_product_name' => 'After Product Name', 'after_product_subtotal' => 'After Product Subtotal )`

@diwakar2000 @Asok17

**Comment by Asok17** [comment]
For the value, `After Product Subtotal` of the option, `Save For Later Button Position`, save for later button is being displayed in checkout page too. The button should be displayed in cart page only.

@diwakar2000

**Comment by diwakar2000** [comment]
save for later button appearing in checkout page fixed in #274

**Comment by Asok17** [comment]
All listed issues have been fixed.
